@api = http://localhost:3001/api/product
@login = http://localhost:3001/api/login
###
GET {{api}}
###

PUT  {{api}}/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZFVzdWFyaW8iOjIsIkdtYWlsIjoiRGVsYXJvc2FAZ21haWwuY29tIiwiUm9sZUlkIjoxLCJpYXQiOjE2MzQyODIzMTZ9.TqR0Y1LY46AmlxjJ7T52ihcSaTxLD8j18IkOo5qfzNg

{
    "Nombre":"Pan sobado",
    "Cantidad":100
}
###

POST  {{api}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZFVzdWFyaW8iOjIsIkdtYWlsIjoiRGVsYXJvc2FAZ21haWwuY29tIiwiUm9sZUlkIjoxLCJpYXQiOjE2MzQyODIzMTZ9.TqR0Y1LY46AmlxjJ7T52ihcSaTxLD8j18IkOo5qfzNg

{
    "Nombre":"Agua",
    "Cantidad":1
}
###
DELETE {{api}}/1
###
POST {{login}}/signUp
Content-Type: application/json

{
    "Gmail":"Eduardo@gmail.com",
    "Clave":"godofwar2"
}
###
POST {{login}}/signIn
Content-Type: application/json

{
    "Gmail":"Eduardo@gmail.com",
    "Clave":"godofwar2"
}
###
GET {{api}}

###
